name: preview
on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.label.name == 'preview' || contains(github.event.pull_request.labels.*.name, 'preview')
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: sofatutor/pullpreview@sofatutor
        with:
          admins: mfittko
          always_on: master
          app_path: .
          instance_type: nano_2_0
          dns: p.sofatutor-sandbox.de
          ports: 53/tcp,53/udp
          registries: docker://index.docker.io/v1
          compose_files: docker-compose.yml
        env:
          DOMAIN: p.sofatutor-sandbox.de
          AWS_REGION: eu-central-1
          PULLPREVIEW_LAUNCH_COMMAND: IP="$(ec2-metadata | grep public-ipv4 | cut -d ' ' -f2)" DOMAIN=$DOMAIN docker-compose up -d --build --force-recreate
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
