name: Preview Cleanup
on:
  pull_request:
    types: [unlabeled, closed]

jobs:
  destroy:
    if: github.event.label.name == 'preview' || contains(github.event.pull_request.labels.*.name, 'preview')
    name: Destroy
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: sofatutor/pullpreview@sofatutor
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "eu-central-1"
